apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: analytics-ai-backend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      containers:
      - name: backend
        image: gcr.io/PROJECT_ID/analytics-ai-backend:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: DATABASE_PATH
          value: "/tmp/analytics_ai.db"
        - name: PYTHONPATH
          value: "/app"
        - name: PROJECT_ID
          value: "PROJECT_ID"
        - name: DEFAULT_BUCKET
          value: "ai-analysis-default-bucket"
        - name: FRONTEND_URL
          value: "https://analytics-ai-frontend-xxxxxxxxx-uc.a.run.app"
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8000"
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 2Gi
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir: {}
  traffic:
  - percent: 100
    latestRevision: true
