apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: analytics-ai-frontend
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        # Cost optimization: Set minimum instances to 0 for on-demand scaling
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
        # CPU throttling for cost savings
        run.googleapis.com/cpu-throttling: "true"
        # Execution environment
        run.googleapis.com/execution-environment: gen2
    spec:
      # Container configuration
      containerConcurrency: 1
      timeoutSeconds: 60
      containers:
      - image: gcr.io/ai-analysis-v1/analytics-ai-frontend:latest
        ports:
        - containerPort: 8080
        env:
        # Backend API URL
        - name: BACKEND_URL
          value: "https://analytics-ai-backend-PLACEHOLDER-uc.a.run.app"
        # Resource limits for cost optimization
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
        # Health checks
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true
