apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: analytics-ai-frontend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      containers:
      - name: frontend
        image: gcr.io/PROJECT_ID/analytics-ai-frontend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: BACKEND_URL
          value: "https://analytics-ai-backend-xxxxxxxxx-uc.a.run.app"
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true
